### PR TITLE
Fix doc moving groups

### PR DESCRIPTION
**Pull request by bookis**
- add ability to move a record with an existing rank to a new group
- refactor group rank test and test helper to create docs
- refactor ranking method and group insert test
- add test cases for inserting at top and end in new group
- refactor Paragraph1 -> GroupedParagraph to avoid constant rename warnings

### CODE REVIEW

**Review by sentientmonkey — APPROVED** [review]
🦀 🛥️

**Comment by richardboehme** [comment]
Hey, this looks like a great change! Would you mind upstreaming it to the main repo?

**Comment by bookis** [comment]
Hey @richardboehme! Thanks for making this!

The intention was to contribute back, just hadn’t gotten around to it 😅 You can probably expect more in the future.

**Comment by richardboehme** [comment]
Sorry @bookis I didn't mean to rush you on this! 😅 I'm really looking forward to future contributions!

**Pull request merged**
